name: Deploy Fantail project to Github Pages
description: "Easily build and deploy your Fantail projects to Github Pages"
inputs:
  nix-flake-ref:
    description: "The nix flake reference to build"
    default: ".#fantailProject"

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v21
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run `nix build`
      shell: bash
      run: nix build ${{ github.event.inputs.nix-flake-ref }}
    - name: Upload build artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./result
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
